application_api_version: v1beta1
properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  NUODB_OPERATOR_IMAGE:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  SERVICE_ACCOUNT:
    type: string
    title: Cluster Admin Service Account
    description: >-
      Name of a service account in the target namespace that
      has cluster-admin permissions. This is needed for the operator
      to create Nuodb CRD's.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups:
            - '*'
            resources:
            - '*'
            verbs:
            - '*'
          - nonResourceURLs:
            - '*'
            verbs:
            - '*'
required:
- APP_INSTANCE_NAME
- NAMESPACE
- NUODB_OPERATOR_IMAGE
- SERVICE_ACCOUNT
